//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace TerminalMACS.I18nResources
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey AppTitle = new ComponentResourceKey(typeof(UiResources), nameof(AppTitle));
	}
}