//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalMACS.Clients.App.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalMACS.Clients.App.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About_MenuItem {
            get {
                return ResourceManager.GetString("About_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Info 的本地化字符串。
        /// </summary>
        public static string ClientInfo_MenuItem {
            get {
                return ResourceManager.GetString("ClientInfo_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile Client 1.0 - Xmarin.Forms 的本地化字符串。
        /// </summary>
        public static string ClientName_AboutPage {
            get {
                return ResourceManager.GetString("ClientName_AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        public static string Contacts_MenuItem {
            get {
                return ResourceManager.GetString("Contacts_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooperation website 的本地化字符串。
        /// </summary>
        public static string CooperationWebsite_AboutPage {
            get {
                return ResourceManager.GetString("CooperationWebsite_AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Idiom 的本地化字符串。
        /// </summary>
        public static string DeviceIdiom {
            get {
                return ResourceManager.GetString("DeviceIdiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Manufacturer 的本地化字符串。
        /// </summary>
        public static string DeviceManufacturer {
            get {
                return ResourceManager.GetString("DeviceManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Model 的本地化字符串。
        /// </summary>
        public static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Name 的本地化字符串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Platform 的本地化字符串。
        /// </summary>
        public static string DevicePlatform {
            get {
                return ResourceManager.GetString("DevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Type 的本地化字符串。
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Version 的本地化字符串。
        /// </summary>
        public static string DeviceVersionString {
            get {
                return ResourceManager.GetString("DeviceVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official website 的本地化字符串。
        /// </summary>
        public static string OfficialWebsite_AboutPage {
            get {
                return ResourceManager.GetString("OfficialWebsite_AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task was cancelled 的本地化字符串。
        /// </summary>
        public static string TaskCancelled {
            get {
                return ResourceManager.GetString("TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Title_AboutPage {
            get {
                return ResourceManager.GetString("Title_AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic information of client 的本地化字符串。
        /// </summary>
        public static string Title_ClientInfoPage {
            get {
                return ResourceManager.GetString("Title_ClientInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        public static string Title_ContactPage {
            get {
                return ResourceManager.GetString("Title_ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View source code 的本地化字符串。
        /// </summary>
        public static string ViewSourceCode_AboutPage {
            get {
                return ResourceManager.GetString("ViewSourceCode_AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to give your valuable comments 的本地化字符串。
        /// </summary>
        public static string WelcomeComments_AboutPage {
            get {
                return ResourceManager.GetString("WelcomeComments_AboutPage", resourceCulture);
            }
        }
    }
}
